#!/bin/bash

PROJECT_NAME="{{.Project}}"


mkdir -p app/api app/core app/models app/schemas app/services app/db

touch app/__init__.py
touch app/api/__init__.py
touch app/core/__init__.py
touch app/models/__init__.py
touch app/schemas/__init__.py
touch app/services/__init__.py
touch app/db/__init__.py

cat > app/main.py <<EOF
from fastapi import FastAPI
from app.api import user

app = FastAPI(title="$PROJECT_NAME")

@app.get("/health")
def health():
    return {"status":"ok"}

app.include_router(user.router, prefix="/api")
EOF

cat > app/api/user.py <<EOF
from fastapi import APIRouter

router = APIRouter()

@router.get("/users")
def get_users():
    return {"users":[]}
EOF

cat > requirements.txt <<EOF
fastapi
uvicorn[standard]
EOF

cat > README.md <<EOF
# $PROJECT_NAME

Generated by Archy 🚀

## Getting Started

1. Create a virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows use \`venv\Scripts\activate\`
   \`\`\`

2. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

3. Run the application:
   \`\`\`bash
   uvicorn app.main:app --reload
   \`\`\`
EOF

# Optional: Initialize git
# git init
