#!/bin/bash

PROJECT_NAME="{{.ProjectName}}"


# Create 3 services
for i in {1..3}
do
    SERVICE_NAME="service-$i"
    mkdir -p "$SERVICE_NAME"/app/{api,core,models,schemas,services,db}

    touch "$SERVICE_NAME"/app/__init__.py
    touch "$SERVICE_NAME"/app/api/__init__.py
    touch "$SERVICE_NAME"/app/core/__init__.py
    touch "$SERVICE_NAME"/app/models/__init__.py
    touch "$SERVICE_NAME"/app/schemas/__init__.py
    touch "$SERVICE_NAME"/app/services/__init__.py
    touch "$SERVICE_NAME"/app/db/__init__.py

    cat > "$SERVICE_NAME"/app/main.py <<EOF
from fastapi import FastAPI

app = FastAPI(title="$SERVICE_NAME")

@app.get("/health")
def health():
    return {"status":"ok", "service": "$SERVICE_NAME"}
EOF

    cat > "$SERVICE_NAME"/app/api/user.py <<EOF
from fastapi import APIRouter
router = APIRouter()

@router.post("/users")
def create_user():
    return {"created":True, "service": "$SERVICE_NAME"}
EOF

    cat > "$SERVICE_NAME"/requirements.txt <<EOF
fastapi
uvicorn[standard]
EOF

    cat > "$SERVICE_NAME"/README.md <<EOF
# $SERVICE_NAME

Generated by Archy 🚀
EOF
    # Dockerfile
    if [ "$USE_DOCKER" = "true" ]; then
        cat > "$SERVICE_NAME"/Dockerfile <<EOF
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "$((8000 + i))"]
EOF
    fi
done

# Root Docker Compose
if [ "$USE_DOCKER" = "true" ]; then
    cat > docker-compose.yml <<EOF
version: '3.8'
services:
  service-1:
    build: ./service-1
    ports:
      - "8001:8001"
  service-2:
    build: ./service-2
    ports:
      - "8002:8002"
  service-3:
    build: ./service-3
    ports:
      - "8003:8003"
EOF
fi

# Root Test Script
if [ "$USE_TEST_SCRIPT" = "true" ]; then
    cat > test.sh <<EOF
#!/bin/bash
echo "Testing services..."
for i in {1..3}
do
    PORT=\$((8000 + i))
    echo "Checking service-\$i on port \$PORT..."
    curl -s http://localhost:\$PORT/health | grep "ok" && echo "service-\$i is UP" || echo "service-\$i is DOWN"
done
EOF
    chmod +x test.sh
fi


