#!/bin/bash

PROJECT_NAME="{{.ProjectName}}"


mkdir -p app/routes app/models app/services app/core

touch app/__init__.py
touch app/routes/__init__.py
touch app/models/__init__.py
touch app/services/__init__.py
touch app/core/__init__.py

cat > app/main.py <<EOF
from flask import Flask
from app.routes.user import user_bp

def create_app():
    app = Flask(__name__)
    app.register_blueprint(user_bp, url_prefix="/api")

    @app.route("/health")
    def health():
        return {"status":"ok"}

    return app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)
EOF

cat > app/routes/user.py <<EOF
from flask import Blueprint

user_bp = Blueprint("user", __name__)

@user_bp.route("/users")
def users():
    return {"users":[]}
EOF

cat > requirements.txt <<EOF
flask
EOF

cat > README.md <<EOF
# $PROJECT_NAME

Generated by Archy 🚀

## Getting Started

1. Create a virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate
   \`\`\`

2. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

3. Run the application:
   \`\`\`bash
   python app/main.py
   \`\`\`
EOF

# Dockerfile
if [ "$USE_DOCKER" = "true" ]; then
    cat > Dockerfile <<EOF
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "app/main.py"]
EOF
fi


